// FILM.TIMELINE: the shot list and audio cue list for "The life of an Arctic tern".
// Owner: storyboard. Human-readable plan: docs/storyboard.md. Visual rules: docs/art-bible.md.
// 120 bpm: a beat is 0.5 s (12 frames at 24 fps). Every shot boundary sits on the beat grid.
(function () {
  'use strict';
  const FILM = window.FILM;

  FILM.TIMELINE = {
    title: 'The life of an Arctic tern',
    bpm: 120,
    duration: 32,
    fps: 24,
    width: 1080,
    height: 1920,
    shots: [
      {
        id: 'hero-hover',
        file: '01-hero-hover.js',
        start: 0,
        end: 1.5,
        mode: 'illustrated',
        title: 'Cold open: the tern with a fish',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'An adult Arctic tern in breeding plumage hovers in side view on G5 over a hatched sea, a sand eel crosswise in its blood-red bill, and frame 0 is fully drawn. The raised wings sweep down in three drawings and snap back up on the 0.5 s beat as a yellow ring bursts from the body. Black cap, white cheek stripe, grey underparts, translucent primaries with a thin black trailing edge, very short red legs tucked.',
      },
      {
        id: 'egg-blueprint',
        file: '02-egg-blueprint.js',
        start: 1.5,
        end: 4,
        mode: 'schematic',
        title: 'A spark, an egg',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A white spark on near-black navy settles on the blastodisc of a lavender blueprint egg lying on its side on a pebble band (G1: 760 px long, blunt end left, pore lattice, blotch outlines, air cell). The nucleus divides 1, 2, 4, 8 on the beats and 16ths and condenses into a curled embryo facing the air cell. Magenta flashes mark the spark, division and the pip signal. Owns the canonical cycle ring helper.',
      },
      {
        id: 'egg-hatch',
        file: '03-egg-hatch.js',
        start: 4,
        end: 5.5,
        mode: 'illustrated',
        title: 'Pipping on the shingle',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Match cut to the inked olive-buff blotched egg on the same G1 pixels, lying in a shingle scrape. A star crack opens at the pip point, a ring crack runs round the blunt end on the beat, the camera pulls back to zoom 0.45 revealing the sibling egg, and the cap tips off as a wet grey speckled chick spills out and fluffs.',
      },
      {
        id: 'chick-feeding',
        file: '04-chick-feeding.js',
        start: 5.5,
        end: 8,
        mode: 'illustrated',
        title: 'Four fish, four days',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A low view across the colony shingle to Young Sound. On the beats 6.0, 6.5, 7.0 and 7.5 a parent lands with a sand eel and the chick swallows it head first, then snaps a size larger (day 1, 6, 11, 16: down, then pin feathers, then grey feathers). A yellow tally ring fills one segment per fish and a blue ruler measures the chick.',
      },
      {
        id: 'growth-ladder',
        file: '05-growth-ladder.js',
        start: 8,
        end: 9.5,
        mode: 'schematic',
        title: 'Thirteen grams to a hundred',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Blueprint ladder of five chick silhouettes, day 0 to day 20, stacked from small at the top to the juvenile at the bottom, each with a mass bracket (13, 30, 60, 90, 104 g). Pin feathers glow on days 10 and 15, and the day-20 juvenile stands up with half-raised wings on the last beat.',
      },
      {
        id: 'wing-stretch',
        file: '06-wing-stretch.js',
        start: 9.5,
        end: 11.5,
        mode: 'illustrated',
        title: 'Down becomes wings',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A juvenile on a shingle rock (black bill, white forehead, dark carpal bar, scaly fringed mantle, short tail) stands up as its last down tufts blow away, opens its wings half-way, then stretches them up into the tall V of G2 on the 11.0 beat and holds.',
      },
      {
        id: 'pin-feather',
        file: '07-pin-feather.js',
        start: 11.5,
        end: 13,
        mode: 'schematic',
        title: 'A feather unrolls from its sheath',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Match cut to the G2 bird in lavender. One primary shows rolled in its sheath with a blood core; the sheath splits at the tip in magenta and the vane unrolls from tip to base, shown in a cross-section cutaway and two small insets, then every primary unrolls in a ripple.',
      },
      {
        id: 'midnight-sun',
        file: '08-midnight-sun.js',
        start: 13,
        end: 16,
        mode: 'illustrated',
        title: 'Days under a sun that never sets',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The juvenile on a boulder by the fjord shore practises flapping while the sun circles low around the sky three times without setting, its dotted path an ellipse above the hills. A day tally ring lights a notch per circuit, the sea glitter follows the sun, and the bird crouches ready at the end.',
      },
      {
        id: 'first-flight',
        file: '09-first-flight.js',
        start: 16,
        end: 18,
        mode: 'illustrated',
        title: 'First flight',
        transitionIn: { kind: 'flash', dur: 0.125 },
        brief: 'On the midpoint downbeat a cream flash reveals the juvenile airborne above the boulder. It beats up toward the camera in four wingbeats as rings burst, banks overhead and arrives exactly on G3 seen from below: wings fully spread, translucent primaries, black bill, short tail.',
      },
      {
        id: 'wing-schematic',
        file: '10-wing-schematic.js',
        start: 18,
        end: 19.5,
        mode: 'schematic',
        title: 'Hand and arm, primaries and lift',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Match cut to G3 in lavender. The wing bones draw on, the ten primaries on the hand light in a run, node glyphs show the hand, the forearm and an airfoil section, streamlines flow over the right wing with lift arrows, and the camera eases toward the push-in target on P8.',
      },
      {
        id: 'feather-mosaic',
        file: '11-feather-mosaic.js',
        start: 19.5,
        end: 22,
        mode: 'illustrated',
        title: 'Push-in: barbs, barbules, hooks',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'One continuous push from the inked underwing into primary P8: the vane of parallel barbs, then barbs with grooved and hooked barbules, then the hooklets at 40x; a split in the vane zips shut hook by hook on the last beat.',
      },
      {
        id: 'two-summers',
        file: '12-two-summers.js',
        start: 22,
        end: 23.5,
        mode: 'schematic',
        title: 'Chasing the light pole to pole',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A lavender globe centred on the Atlantic. The day-night terminator swings from June (Arctic lit) to December (Antarctic lit) while a tern marker steps from Sand Island to the Weddell Sea, always on the day side; a magenta ring marks its arrival.',
      },
      {
        id: 'pull-back-atlantic',
        file: '13-pull-back-atlantic.js',
        start: 23.5,
        end: 26.5,
        mode: 'illustrated',
        title: 'Pull-back: colony, fjord, Greenland, Atlantic',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A continuous zoom-out from the Sand Island colony to the island, the fjord and the Greenland coast, landing on the engraved Atlantic map (G4). The route draws on: stopover box, the split at 10 N into the Africa and Brazil legs, the Weddell Sea ring, then the blue S-shaped return track.',
      },
      {
        id: 'ocean-flock',
        file: '14-ocean-flock.js',
        start: 26.5,
        end: 28,
        mode: 'illustrated',
        title: 'Riding the winds south',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Open ocean swells under a big sky: four loose groups of terns (never a V) fly toward the lower left on curved blue wind lines, black-billed autumn birds, one lead bird ringed; they bank on the beat and glide on a gust.',
      },
      {
        id: 'pack-ice',
        file: '15-pack-ice.js',
        start: 28,
        end: 29.5,
        mode: 'illustrated',
        title: 'Summer on the Antarctic ice',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The Weddell Sea pack-ice edge under a low sun: winter-plumage terns (white foreheads, black bills) rest on floes, one showing a moult gap, feathers drift, five month circles fill Dec to Apr, then the birds lift off north on the 29.0 beat.',
      },
      {
        id: 'return-egg',
        file: '16-return-egg.js',
        start: 29.5,
        end: 30.5,
        mode: 'illustrated',
        title: 'Home: a new egg',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Back on the Sand Island shingle, a red-billed mate lands and offers a sand eel at a scrape with two eggs; on the 30.0 beat the camera snap-zooms 20x onto the first egg, landing exactly on G1.',
      },
      {
        id: 'egg-loop',
        file: '17-egg-loop.js',
        start: 30.5,
        end: 32,
        mode: 'schematic',
        title: 'Back to the egg',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The 02 blueprint egg fully drawn on G1 with its single nucleus; the cycle ring closes with a flash, the wordmark "arctic tern" fades in, and the frame settles for the loop.',
      },
    ],
    cues: [
      { t: 0, kind: 'hit', note: 'Bar 1 downbeat: felt kick, FM marimba E major add9 chord, sine sub E2' },
      { t: 0.083, kind: 'sfx', note: 'Rising wing flutter, band-passed noise sweeping up' },
      { t: 0.5, kind: 'hit', note: 'Wing snap: downward whoosh and sub drop as the ring bursts; kalimba motif E5 G#5 B5 F#5 on 8ths; tern call glide 2.8 to 2.2 kHz' },
      { t: 1, kind: 'sfx', note: 'Small wing flutter' },
      { t: 1.5, kind: 'cut', note: 'Everything drops out: glassy sine ping E6 with long generated reverb for the spark' },
      { t: 2, kind: 'swell', note: 'Reverse swell under the egg outline draw; glide 3 kHz to 1.2 kHz over 250 ms' },
      { t: 2.5, kind: 'sfx', note: 'Rising 16th bell arpeggio, E major pentatonic, tracking the lattice sweep' },
      { t: 3, kind: 'sfx', note: 'Division: two pings B5 and E6' },
      { t: 3.25, kind: 'sfx', note: 'Division: four pings in 32nds' },
      { t: 3.5, kind: 'sfx', note: 'Division: eight-ping ripple' },
      { t: 3.75, kind: 'sfx', note: 'Pip signal crackle: three high-passed noise clicks' },
      { t: 4, kind: 'cut', note: 'Bar 3: woody tock and warm pluck chord return (illustrated timbre)' },
      { t: 4.25, kind: 'sfx', note: 'Tiny dry tick, first crack' },
      { t: 4.5, kind: 'hit', note: 'Ring crack: filtered-noise crack with pitched pop B4, then lowpassed whoosh across the pull-back' },
      { t: 5, kind: 'sfx', note: 'Cap tips over: hollow clack E5 with a pebble rattle' },
      { t: 5.25, kind: 'sfx', note: 'Chick peep: sine chirp 3.5 to 4 kHz' },
      { t: 5.5, kind: 'cut', note: 'Chick peeps on 16ths L/R, small bright shaker' },
      { t: 6, kind: 'hit', note: 'Feed 1: wing whump, pebble crunch, FM boop E4, gulp click' },
      { t: 6.5, kind: 'hit', note: 'Feed 2: whump, crunch, boop G#4, gulp' },
      { t: 7, kind: 'hit', note: 'Feed 3: whump, crunch, boop B4, gulp; shaker 8ths enter' },
      { t: 7.5, kind: 'hit', note: 'Feed 4: whump, boop E5, parent call as it lifts off' },
      { t: 8, kind: 'cut', note: 'Bar 5: five rising glass bell ticks on 16ths over a sub swell' },
      { t: 8.5, kind: 'sfx', note: 'Feathers break through: soft FM bell' },
      { t: 9, kind: 'sfx', note: 'Upward pitch-bend whoosh as the juvenile stands' },
      { t: 9.5, kind: 'cut', note: 'Tock and pluck' },
      { t: 10, kind: 'sfx', note: 'Low stretch creak' },
      { t: 10.5, kind: 'sfx', note: 'Wing unfold: bandpass noise 400 Hz to 3 kHz over 200 ms' },
      { t: 11, kind: 'hit', note: 'Wings up: bright chord stab; rising plucks B4 E5 G#5 on 11.0, 11.125, 11.25' },
      { t: 11.5, kind: 'cut', note: 'Glass ping and sub swell' },
      { t: 11.583, kind: 'sfx', note: 'Rising glide as the glow climbs the feather core' },
      { t: 12, kind: 'sfx', note: 'Sheath split: crisp paper-tear crackle' },
      { t: 12.5, kind: 'sfx', note: 'Vane unrolls: fast glock arpeggio E6 down to E5 over 6 frames' },
      { t: 12.75, kind: 'sfx', note: 'Ripple of 8 small pings' },
      { t: 13, kind: 'cut', note: 'Tock and pluck; sustained high pad in open fifths for the endless day' },
      { t: 13.5, kind: 'sfx', note: 'Soft flutter burst' },
      { t: 13.958, kind: 'sfx', note: 'Day 1 ting, FM B5' },
      { t: 14.5, kind: 'sfx', note: 'Bigger flutter burst' },
      { t: 14.958, kind: 'sfx', note: 'Day 2 ting, FM C#6' },
      { t: 15.5, kind: 'sfx', note: 'Hop: woody tock' },
      { t: 15.958, kind: 'sfx', note: 'Day 3 ting, FM E6' },
      { t: 16, kind: 'hit', note: 'Bar 9 midpoint: crash, full kick, full chord, kalimba motif an octave up; first wingbeat whump' },
      { t: 16.25, kind: 'sfx', note: 'Wingbeat whump' },
      { t: 16.5, kind: 'hit', note: 'Wingbeat whump and bright rising whoosh with the rings' },
      { t: 16.75, kind: 'sfx', note: 'Wingbeat whump' },
      { t: 17, kind: 'sfx', note: 'Sustained tern call kee-ar' },
      { t: 17.5, kind: 'swell', note: 'Pad opens' },
      { t: 18, kind: 'cut', note: 'Glass ping and bells' },
      { t: 18.5, kind: 'sfx', note: '10-note glock run up E major on 32nds, one per primary' },
      { t: 19, kind: 'swell', note: 'Airy swell, band-passed noise 800 Hz to 2 kHz, for the airflow' },
      { t: 19.5, kind: 'cut', note: 'Rising filtered sweep for the push-in' },
      { t: 20, kind: 'hit', note: 'Zoom thump, sub drop E2' },
      { t: 20.5, kind: 'hit', note: 'Zoom thump, sub drop B1' },
      { t: 21, kind: 'hit', note: 'Zoom thump, sub drop E1' },
      { t: 21.5, kind: 'sfx', note: 'Zipper: 12 tiny clicks on 32nds panned L to R, soft chord resolution' },
      { t: 22, kind: 'cut', note: 'Glass ping, pad on the IV chord' },
      { t: 22.5, kind: 'sfx', note: 'Descending 8th plucks as the marker moves south' },
      { t: 23, kind: 'hit', note: 'Bright bell and magenta stab at the Weddell Sea' },
      { t: 23.5, kind: 'cut', note: 'Wind and surf wash, colony kip chatter' },
      { t: 24, kind: 'sfx', note: 'Pull-out whoosh 1' },
      { t: 24.5, kind: 'sfx', note: 'Pull-out whoosh 2, lower' },
      { t: 25, kind: 'hit', note: 'Pull-out whoosh 3 landing on the map; travelling marimba 8ths follow the route' },
      { t: 26, kind: 'swell', note: 'Gong-like swell at the Weddell Sea' },
      { t: 26.25, kind: 'sfx', note: 'Fast rising arpeggio for the S-shaped return track' },
      { t: 26.5, kind: 'cut', note: 'Wind pad, distant kip calls panned' },
      { t: 27, kind: 'sfx', note: 'Gust whoosh as the flock banks' },
      { t: 27.5, kind: 'sfx', note: 'Soaring horn line, motif E5 G#5 B5 F#5' },
      { t: 28, kind: 'cut', note: 'Cold high pad with slow tremolo, ice creaks' },
      { t: 28.25, kind: 'sfx', note: 'Month ting, Jan' },
      { t: 28.5, kind: 'sfx', note: 'Month ting, Feb' },
      { t: 28.75, kind: 'sfx', note: 'Month ting, Mar' },
      { t: 29, kind: 'hit', note: 'Month ting Apr; rising wing burst and bright call as the flock lifts off' },
      { t: 29.5, kind: 'cut', note: 'Tock, pluck and colony calls' },
      { t: 29.75, kind: 'sfx', note: 'Fish-flight call pair' },
      { t: 30, kind: 'swell', note: 'Fast rising whoosh for the snap zoom' },
      { t: 30.5, kind: 'cut', note: 'Glass ping E6, pad on the tonic' },
      { t: 31, kind: 'sfx', note: 'Soft bell chord for the wordmark' },
      { t: 31.5, kind: 'swell', note: 'Reverse swell into the loop downbeat, level matched to bar 1' },
    ],
  };
})();
